Add instructions to default project

diff --git a/.diploi/helm/app.yaml b/.diploi/helm/app.yaml
--- a/.diploi/helm/app.yaml
+++ b/.diploi/helm/app.yaml
@@ -59,10 +59,10 @@ spec:
             - /bin/sh
             - -c
             - |
-              if [ -f yarn.lock ]; then yarn run build \
-              elif [ -f package-lock.json ]; then npm run build \
-              elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build \
-              else echo "Lockfile not found." && exit 1 \
+              if [ -f yarn.lock ]; then yarn run build; \
+              elif [ -f package-lock.json ]; then npm run build; \
+              elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+              else echo "Lockfile not found." && exit 1; \
               fi &&
               rm -rf /build/{*,.*} &&
               (shopt -s dotglob; mv -v ./* /build) ||:
